name: ci

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.11.4"

      - name: Format
        if: matrix.os == 'ubuntu-latest'
        run: deno fmt --check

      - name: Test 
        run: deno test --unstable --allow-net